spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/currency_db
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  mvc:
    converters:
      preferred-json-mapper: jackson
    media-types:
      xml: application/xml

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
    time-to-live: 600000

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 10
          max-interval: 10000
          multiplier: 2.0